services:
  mysql:
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '8888:8080'
    depends_on:
      - mysql

volumes:
  mysql_data: